# Generated by Django 2.2.2 on 2019-06-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poducts',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='poducts',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='poducts',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
