# Generated by Django 2.2.2 on 2019-06-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190627_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poducts',
            name='code',
        ),
    ]
