# Generated by Django 2.2.2 on 2019-06-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_poducts_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poducts',
            new_name='Products',
        ),
    ]
