# Generated by Django 2.2.2 on 2019-06-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190628_1726'),
        ('products', '0006_auto_20190629_1824'),
    ]

    operations = [
    ]
